# this is the top-level docker-compose.yml that
# orchestrates the deployment of all services.
include:
  - path:
    - ./services/CTFd/CTFd/docker-compose.yml
    - ./services/CTFd/docker-compose.override.yml
  - path: ./docker-compose.common.yml
    project_directory: .

