# This is primarily intended to run Cybersword
# with HTTPs on a Digital Ocean droplet.
# We assume that if we're running on NKCyber
# hardware, that we'll be serving HTTP,
# which will get a cert via nginx proxy manager.

# this is the top-level docker-compose.yml that
# orchestrates the deployment of all services.
include:
  - path:
    - ./services/CTFd/CTFd/docker-compose.yml
    - ./services/CTFd/docker-compose.https.override.yml
  - path: ./docker-compose.common.yml
    project_directory: .

