# this is the top-level docker-compose.yml that
# orchestrates the deployment of all services.
version: "3.8"
include:
  - path:
    - ./services/CTFd/CTFd/docker-compose.yml
    - ./services/CTFd/docker-compose.https.override.yml
  - path: ./services/judge0/docker-compose.yml
    project_directory: ./services/judge0
  - path: ./services/judge0-ide/docker-compose.yml
    project_directory: ./services/judge0-ide
  - path: ./services/ai-hacking-lab/docker-compose.yml
    project_directory: "."
services:
  # TODO: move these into an easily include-able file
  sql-injection-lab:
    build:
      context: . # build relative to current dir
      dockerfile: ./services/sql-injection-lab/Dockerfile
  judge0-wrapper:
    build:
      context: . # build relative to current dir
      dockerfile: ./services/judge0-wrapper/Dockerfile

