# This is used by the docker-compose.https.yml
# in the root project dir. This depends on
# setting up https for your domain with certbot.
services:
  nginx:
    volumes:
      # note that paths are relative to docker-compose.yml in the CTFd subdirectory
      - ../nginx.https.override.conf:/etc/nginx/nginx.conf
      - ../location-defaults.conf:/etc/nginx/location-defaults.conf
      - ../gotty-defaults.conf:/etc/nginx/gotty-defaults.conf
      - ../locations.conf:/etc/nginx/locations.conf
      - ../upstreams.conf:/etc/nginx/upstreams.conf
      - /etc/letsencrypt/cybersword/fullchain.pem:/certificates/fullchain.pem:ro
      - /etc/letsencrypt/cybersword/privkey.pem:/certificates/privkey.pem:ro
    ports:
      # - 80:80
      - 443:443
