version: "3.9"

services:
    judge0-ide:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./ide:/app/files:ro
        restart: always
        ports:
            - "8015:8015"
