# THIS IS INTENDED TO BE INCLUDED BY THE TOP LEVEL DOCKER COMPOSE.
# IT WILL NOT WORK PROPERLY RUNNING FROM THIS CONTEXT

services:
  ai-hacking-lab:
    build:
      context: . # build relative to current dir
      dockerfile: ./services/ai-hacking-lab/Dockerfile
    depends_on:
      - "ai-redis"
      - "ollama"
    restart: always
    ports:
      - "8006:8006"
  ai-redis:
    image: "redis:7.2"
    ports:
      - "6380:6380"
    restart: always
    command: "redis-server --port 6380"
  ollama:
    build:
      context: . # build relative to current dir
      dockerfile: ./services/ai-hacking-lab/OLLAMA_Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama
    restart: "unless-stopped"

volumes:
  ollama_volume:
